---
title: "Capitulo 8 Problema 2 Romer"
author: "Germán Campos Ortíz"
date: "26/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 8.2 

**Problema**: El ingreso promedio de los agricultores es menor que el ingreso promedio de los no agricultores, pero fluctua más de un año a otro. 
De acuerdo a lo anterior, ¿Cómo predice la hipótesis del ingreso permanente el hecho de que las funciones de consumo estimadas para agricultores y no agricultores difieran? 

**Solución**: 

Inicialmente suponemos que el ingreso corriente del individuo *i* en el periodo *t* es la suma de su ingreso permanente y su ingreso transitorio, es decir: 

$$
Y _{it} = Y _i ^P + Y _{it} ^T
$$

Así mismo, suponemos que no hay variaciones en las cantidades que los individuos desean consumir a lo largo del tiempo, es decir, la función de utilidad $u(\bullet)$ es la misma en cada periodo. Utilizamos la siguiente función de utilidad: 

$$
U _i = \sum _{t=1} ^{T} u(C _{it} - e _{it})
$$

Suponemos que $e_{it}$ tiene media igual a 0 y no está correlacionada con $Y _i ^P$ y $Y _i ^T$. A su vez, suponemos un modelo sin incertidumbre, por lo cual, cada individuo conocerá los valores que tomará su  $e_{it}$. Dado que la media de $e_{it}$ durante la vida de cada individuo es igual a 0, de aquí se deduce que: 

$$
C _{it} = Y _i ^P + e_{it}
$$

En donde $e_{it}$ se le conoce como el consumo transitorio. 

Ahora bien, de la información dada por el problema interpretamos lo siguiente: 

- Consideramos que el ingreso transitorio es, en promedio, igual a cero. Por lo cual, podemos interpretar que el ingreso promedio de cada individuo es igual al ingreso permanente promedio 
- Los agricultores tienen ingresos permanentes más bajos que los no agricultores, a saber:        $\bar{Y} _F ^P < \bar{Y} _{NF} ^P$. Siendo *F* el subindice para los agricultores y           *NF* el de los no agricultores. 

- Si los ingresos de los agricultores fluctuan más de un año a otro llegamos a la idea de que la varianza de los ingresos transitorios de los agricultores es mayor a la varianza de los ingresos transitorios de los no agricultores, lo que indica que $Var(Y _F ^T) > Var (Y _{NF} ^T)$


De acuerdo a los supuestos inicialmente mencionados, podemos considerar el siguiente modelo de regresión 

$$
C _i = a + bY_i + e_i 
$$
En esta ecuación $C_i$es el consumo corriente que, de acuerdo a la hipótesis de la renta permanente, está determinado por el ingreso permanente, de tal forma que $C=Y ^P$. Por su parte, $Y _i$ es el ingreso corriente, el cual es la suma del ingreso permanente y el ingreso transitorio, tal como se dijo anteriormente. 

Aplicando el método de Mínimos Cuadrados Ordinarios para estimar los coeficientes de la anterior regresión llegamos a que: 

$$
\hat{b} = \frac{Cov(Y_i, C_i)}{Var(Y _i)} = \frac{Cov(Y_i ^P + Y _i ^T, Y_i ^P + e _{it})}{Var(Y _i ^P + Y _i ^T )} 
$$

$$
\therefore  \hat{b} = \frac{Var(Y _i ^P)}{Var(Y _i ^P) + Var(Y _i ^T )}
$$

Si consideramos que la $Var(Y ^P)$ es igual en los dos grupos (agricultores y no agricultores), la diferencia en la estimación de $\hat{b}$ será determinada por la diferencia en la $Var(Y _i ^T$ de los dos grupos poblacionales. De esta forma, dado que $Var(Y _F ^T) > Var(Y _{NF} ^T)$, entonces el coeficiente de pendiente estimado ($\hat{b}$) debe ser menor para los agricultores que para los no agricultores, es decir que $\hat{b _F} < \hat{b _{NF}}$.

Lo anterior indica que el impacto estimado en el consumo de un aumento marginal en los ingresos corrientes es menor para el grupo de agricultores que para el grupo de no agricultores. Siguiendo la hipótesis del ingreso permanente esto se debe a que es mucho más probable que el aumento se deba a ingresos transitorios para los agricultores, que para los no agricultores. Por tanto, se puede esperar que el aumento en los ingresos tenga un impacto menor en el consumo de los agricultores, con respecto a los no agricultores. 

Por su parte, la estimación del intercepto ($\hat{a}$) en la regresión nos dice que: 

$$
\hat{a} = \bar{C} - \hat{b}Y 
$$
$$
\hat{a} = Y ^P - \hat{b}(\bar{Y}^P+\bar{Y}^T)
$$
$$
\therefore \hat{a} = (1- \hat{b})\bar{Y}^P
$$

Dado que $\hat{b _F} < \hat{b _{NF}}$, esto indicaría que el intercepto sería mayor para los agricultores que para los no agricultores. Sin embargo, a su vez sabemos que $\bar{Y}_F ^P < \bar{Y}_{NF} ^P$, entonces por esto abría una tendencia a que el intercepto fuera mayor en los agricultores. Por tanto, ante estas dos tendencias contrarias, el resultado de la diferencia del intercepto ($\hat{a}$) es ambiguo para estos dos grupos poblacionales. No obstante, vale la pena considerar que si se analiza el nivel promedio de ingreso permanente de los agricultores, se esperaría que la función de consumo estimada para los agricultores sea inferior con respecto a la función de consumo de los no agricultores. 

